travis:
  secure:
    BINSTAR_TOKEN: cj8Qj5JpaZbWyHMoMoeMxQJVp2fh/QHql8uOURULlms8Bk1IqAK7tp2JLVhI+CRJPlyjbdcOiwf9NH0ePDCdwLz9UCfJdfAx1v45JXu3tXL+4eyma2sHoqX+F9NcDtk4uLeZ94eZgM247Ujuv0kYREHUlRpxtK7M+at3X97WUrPWbe+8SxHyxaMESJs4xYpkZbNHrvxpFEqjV98PwsT++9qEE+zqwMbZSsYZEf+N4fV5fpxdTrHs6GgCNksSXZebp+exzqH79tcn0A9KGlmw0r2Hb3fATQg6DTy+AhTp0H4eDWpq8zxUC+VJQF0vHR3ACtUMiyrWpPhWX7lmzcpMtnE8JqgzHZs2d87vVKuIDvs5vEHV/+d6yRXKu2ygCEsNdn3dafN5kWinG5EgBROkeW6faNU3UnyG4GvAcolqBczX4CF3EZk8vkL2zSJiYX4VR2pdIeNpRHYa2nVht65tN6S6odnE6ppuAQNGkxgXr+pa2IdVVvgnIG10K0knZctQ6laEt6sa7lVwP/7U/3ivVfr08e8i1mA5sp/6zVTt70eOGYtBVCp9E2gSX9V0KOTbbcZNMeZ0hHMQm6d0m6A9a5C7eVmnMxATJ15V0TvAMw2g+a/YmXBO95oS/AfhdTMJc7QX5UHQYtpB60RF0VmObimPhj2w4JBRgtwsWTflUM0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
