travis:
  secure:
    BINSTAR_TOKEN: om2ntSesVe92S01VnsRTVRFVQZsP1Zs0uRsMN1xoY22baZXNsThocOCUrMjP0GSjs5iGLrnmcIYrkJaD/HVZJNCZa09d0pv+c4kPF6ROapSSR5zUvrsaUc82uP1GmcPb/fg3ZECBLaXkldY6H//z3N/09MI0tCc4piNXQHy16GIF+dm5Hf0H0jHZk8pBonuQCM6w8DexFsmQTqf3MSBbjW7bewmEcDM0+yFK7rhDjc1AP0goPjPeRDYM1UsMN85nqKjB07oKP7Umfnmnq+2vpBnsze9X15tK0zVCgMfHnoPIhQW2x1e/prqx9HkpU7nua+BuP+h6466gUgPYM3f6EbayNRBMS9EIw0BhSTPYV4qmvTzMZj/qLbLGq3sB08XIHwElOTgSfXhvkxqSwpFhAZ/IDrPZDFrpN00W/RtTkBvahPdIuSTyuHuipXiewynaQvOe/0001Y421oyH4pmeFCjkbQM/sBVSOXZTjsQy2U5uCU/4Dr0L/PmI/E2fPRNE1I5Q+/yuASXjK+fL9I2gTvHIRQL2ZfZdZYMw38Hr9nWenHFwpbco9ZG7V9duo7YoaBYK7wZ+KCeoJrkcIliUhaRmATtg7RtXrgO1IxO15gXVv+l0MFgejOUZuR4tLWBp4XNfltTIGlFC3i9evxm8LNVucMSfBbNB0EowtQdt310=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
