travis:
  secure:
    BINSTAR_TOKEN: BrgTQCMHtuglceByjyfa30dZoGh9Mwhr5kL1EsTvtXoiOCwBL+JZTb0uqlnakQQ5e2VLB0ecto7InSQxazllJK0lXQjEZXEcEAhB3I+La0aHtUPdqtYrEGimM8OuJmeW+8j5acHKIsa4nz4lKCprhFQLowRWJGdVuwMPqvjEYqZicPAd88HFuTkTi93chec1/cIHr2PfpfA39ZPvoVcJwnDJtvODdsZ9U1VFKErc/92hY8ETAojMg1SIZFFVWkvgbydZXqohSCdfOYEzi0J0486WOwN/qwZvdIrAg8N5IwhfEc8qXXDef/xiT5n4tOQPqcfcFEhRYhuKb0nqobNPhm1PPyL8nd10fpxxbh5xy+QOQvU6XYxlSg/VGcLvHPNs5dqHhzZqjN8efiWhgg095ovQMkrTa7//tXmNzePPvbf3ScXFfdj8ne3NwWxdLm/xn11U/ASqLdJmxxmNOvTomqCARpuRAktAxD8KGiKkc9xIEwvdi/pmujUzeGxPdkbJheuzRLL+4cMOFwCXNBzluUVOegstL6eIGQs4ZWKd3Y7ZBybXLPh93blFBhzc5aSOyLPMGPNEymnXaU/LeU5mmy035XWycabrVH4GLWVcPUXh/DBAB44b4z2SCU6HEG/TWJNXuF7nkG5ScALG1Xrw1Y0yU90UL9iEdawNbosVBUk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
